// ─────────────────────────────────────────────
// PEPTIDE DEFINITIONS
// ─────────────────────────────────────────────
export const peptides = [
  {
    slug: 'bpc-157',
    name: 'BPC-157',
    subtitle: 'Body Protection Compound',
    category: 'Recovery & Healing',
    emoji: '🩹',
    color: '#3B82F6',
    bg: '#EFF6FF',
    overview: `BPC-157 (Body Protection Compound-157) is a synthetic peptide derived from a protein found naturally in human gastric juice. Consisting of 15 amino acids, it has been extensively studied in preclinical research for its remarkable ability to accelerate tissue healing and repair.`,
    mechanism: `BPC-157 works by upregulating growth hormone receptors, promoting angiogenesis (formation of new blood vessels), and modulating nitric oxide signaling pathways. This multi-faceted mechanism enables it to simultaneously address inflammation, promote collagen synthesis, and accelerate cellular repair across multiple tissue types.`,
    uses: ['Tendon & ligament repair', 'Muscle injury recovery', 'Gut health & IBS', 'Joint pain reduction', 'Post-surgical healing', 'Chronic wound healing'],
    effects: 'Users report significant reductions in recovery time from musculoskeletal injuries, improved gut function, reduced joint inflammation, and faster healing from surgical procedures. Most clinical users note results within 2–4 weeks of consistent use.',
    priceRange: '$89–$199/mo',
    peptideIds: ['bpc-157'],
  },
  {
    slug: 'sermorelin',
    name: 'Sermorelin',
    subtitle: 'Growth Hormone Releasing Hormone Analog',
    category: 'Anti-Aging & Hormones',
    emoji: '📈',
    color: '#10B981',
    bg: '#F0FDF4',
    overview: `Sermorelin is a synthetic analog of growth hormone-releasing hormone (GHRH), consisting of the first 29 amino acids of natural GHRH. Unlike direct HGH replacement, sermorelin stimulates the pituitary gland to produce and release its own growth hormone naturally.`,
    mechanism: `Sermorelin binds to GHRH receptors in the anterior pituitary gland, triggering the natural pulsatile release of growth hormone. This approach preserves the body's natural feedback mechanisms, maintaining physiological GH rhythms and avoiding the side effects associated with direct HGH supplementation.`,
    uses: ['Anti-aging & longevity', 'Improved sleep quality', 'Lean muscle support', 'Fat metabolism', 'Energy & vitality', 'Bone density support'],
    effects: 'Patients typically report improved sleep quality within the first 2–3 weeks. Over 3–6 months, users commonly note improvements in body composition (increased lean mass, reduced fat), energy levels, skin quality, and overall sense of vitality.',
    priceRange: '$149–$299/mo',
    peptideIds: ['sermorelin'],
  },
  {
    slug: 'ipamorelin',
    name: 'Ipamorelin',
    subtitle: 'Selective Growth Hormone Secretagogue',
    category: 'Performance & Recovery',
    emoji: '💪',
    color: '#8B5CF6',
    bg: '#F5F3FF',
    overview: `Ipamorelin is a third-generation growth hormone secretagogue (GHS) and a selective agonist of the ghrelin receptor. It is widely regarded as one of the cleanest GH-releasing peptides available due to its high selectivity and minimal side effects.`,
    mechanism: `Ipamorelin selectively stimulates GH release from the pituitary gland without significantly affecting cortisol, prolactin, or ACTH levels — a key advantage over older GH secretagogues like GHRP-2 and GHRP-6. It is commonly combined with CJC-1295 for synergistic GH pulse amplification.`,
    uses: ['Growth hormone optimization', 'Muscle growth & recovery', 'Fat loss support', 'Sleep quality', 'Anti-aging', 'Athletic performance'],
    effects: 'Users report improved sleep quality, enhanced muscle recovery, gradual improvements in body composition, and increased energy. Ipamorelin is often stacked with CJC-1295 for amplified GH pulses. Results typically become noticeable after 4–8 weeks.',
    priceRange: '$129–$249/mo',
    peptideIds: ['ipamorelin'],
  },
  {
    slug: 'tb-500',
    name: 'TB-500',
    subtitle: 'Thymosin Beta-4 Analog',
    category: 'Recovery & Healing',
    emoji: '🔬',
    color: '#EC4899',
    bg: '#FDF2F8',
    overview: `TB-500 is a synthetic version of the naturally occurring peptide Thymosin Beta-4, a protein present in virtually all human cells. It plays a critical role in cell migration, proliferation, and differentiation, making it central to the body's natural healing processes.`,
    mechanism: `TB-500 works by upregulating actin, a cell-building protein essential to healing. It promotes the formation of new blood vessels, reduces inflammation, and facilitates the migration of cells to injury sites. Its systemic nature — ability to travel throughout the body via the bloodstream — makes it particularly effective for widespread or hard-to-reach injuries.`,
    uses: ['Systemic tissue repair', 'Muscle healing', 'Tendon & ligament recovery', 'Inflammation reduction', 'Cardiac tissue support', 'Hair regrowth (off-label)'],
    effects: 'TB-500 is frequently stacked with BPC-157 for what many practitioners describe as a powerful synergistic healing protocol. Users report reduced inflammation, faster recovery from both acute and chronic injuries, and improved flexibility and range of motion.',
    priceRange: '$119–$229/mo',
    peptideIds: ['tb-500'],
  },
  {
    slug: 'nad-plus',
    name: 'NAD+',
    subtitle: 'Nicotinamide Adenine Dinucleotide',
    category: 'Longevity & Energy',
    emoji: '⚡',
    color: '#F59E0B',
    bg: '#FFFBEB',
    overview: `NAD+ (Nicotinamide Adenine Dinucleotide) is a critical coenzyme found in every cell of the body, essential for energy metabolism, DNA repair, and cellular signaling. NAD+ levels naturally decline by 40–60% between ages 20 and 60, and this decline is strongly associated with hallmarks of aging.`,
    mechanism: `NAD+ is a cofactor for over 500 enzymatic reactions, including those performed by sirtuins (the "longevity genes") and PARPs (DNA repair enzymes). Restoring NAD+ levels activates these pathways, supporting mitochondrial function, reducing oxidative stress, and potentially slowing cellular aging processes.`,
    uses: ['Cellular energy production', 'Cognitive function & clarity', 'DNA repair support', 'Metabolic health', 'Longevity & anti-aging', 'Addiction recovery support'],
    effects: 'IV NAD+ therapy is reported to produce rapid boosts in energy and mental clarity. Subcutaneous NAD+ precursor therapy shows more gradual but sustained improvements in energy, cognitive function, and overall vitality over weeks to months.',
    priceRange: '$199–$499/mo',
    peptideIds: ['nad-plus'],
  },
  {
    slug: 'pt-141',
    name: 'PT-141',
    subtitle: 'Bremelanotide — Sexual Health Peptide',
    category: 'Sexual Health',
    emoji: '❤️',
    color: '#EF4444',
    bg: '#FFF1F2',
    overview: `PT-141 (Bremelanotide) is a synthetic peptide melanocortin agonist originally derived from Melanotan II. Unlike PDE5 inhibitors (Viagra, Cialis), PT-141 works through the central nervous system to enhance sexual desire and arousal in both men and women.`,
    mechanism: `PT-141 activates melanocortin receptors (MC3R and MC4R) in the hypothalamus, directly stimulating the dopaminergic pathways involved in sexual arousal. This central mechanism of action means it addresses desire and motivation, not just the physical vascular response, making it effective for both male erectile dysfunction and female hypoactive sexual desire disorder.`,
    uses: ['Male erectile dysfunction', 'Female sexual dysfunction (HSDD)', 'Low libido in men & women', 'Enhanced sexual arousal', 'Post-menopause sexual health'],
    effects: 'PT-141 typically produces noticeable effects within 45–90 minutes of subcutaneous administration. Users report enhanced libido, arousal, and sexual satisfaction. The FDA-approved version (Vyleesi) is licensed for premenopausal women with HSDD.',
    priceRange: '$99–$199/mo',
    peptideIds: ['pt-141'],
  },
  {
    slug: 'cjc-1295',
    name: 'CJC-1295',
    subtitle: 'Long-Acting GHRH Analog',
    category: 'Anti-Aging & Hormones',
    emoji: '🧬',
    color: '#06B6D4',
    bg: '#ECFEFF',
    overview: `CJC-1295 is a long-acting synthetic analog of growth hormone-releasing hormone (GHRH). Unlike natural GHRH which degrades in minutes, CJC-1295 is engineered to remain active in the bloodstream for days, enabling infrequent dosing with sustained GH elevation.`,
    mechanism: `CJC-1295 binds to albumin in the bloodstream via drug affinity complex (DAC) technology, dramatically extending its half-life to 6–8 days. It consistently elevates GH and IGF-1 levels, and is most commonly combined with Ipamorelin to create synergistic, amplified GH pulses.`,
    uses: ['Growth hormone optimization', 'Anti-aging protocols', 'Body recomposition', 'Improved sleep', 'Recovery enhancement', 'Bone density support'],
    effects: 'The CJC-1295/Ipamorelin combination is one of the most popular peptide stacks. Users report improved sleep depth and quality within weeks, followed by gradual improvements in body composition, skin texture, energy, and recovery over 3–6 months.',
    priceRange: '$149–$279/mo',
    peptideIds: ['cjc-1295'],
  },
  {
    {
    slug: 'thymosin-alpha-1',
    name: 'Thymosin Alpha-1',
    subtitle: 'Immune System Optimizer — Approved in 37 Countries',
    category: 'Immune & Longevity',
    emoji: '🛡️',
    color: '#059669',
    bg: '#ECFDF5',
    overview: `Thymosin Alpha-1 is one of the most underappreciated peptides in the longevity space. While BPC-157 and GH peptides get most of the attention, Thymosin Alpha-1 targets something more fundamental: your immune system. It's a naturally occurring peptide produced by the thymus gland — the organ responsible for maturing your T-cells. The thymus begins shrinking after puberty and is largely inactive by your 50s. Thymosin Alpha-1 replaces what a functioning thymus produces. It's approved in 37 countries (sold as Zadaxin) for hepatitis B, C, and as a cancer immunotherapy adjunct. In the US, it's used off-label for immune optimization and longevity protocols.`,
    mechanism: `Thymosin Alpha-1 drives T-cell maturation, activates dendritic cells (the immune system's "scouts"), enhances natural killer (NK) cell activity, and helps immune cells identify and destroy infected or abnormal cells. It makes your immune system smarter and more capable. In chronic infections, it breaks the immune "tolerance" that allows viruses to persist. For longevity, it directly addresses immunosenescence — the gradual decline of immune function that leaves older adults vulnerable to infections, cancer, and inflammatory disease.`,
    uses: ['Immune optimization and resilience', 'Chronic infection support (Lyme, EBV, viral)', 'Post-COVID immune recovery', 'Cancer immunotherapy adjunct', 'Reducing frequency of illness', 'Longevity immune protocols'],
    longevity: `Immunosenescence — the progressive decline of immune function with age — is one of the primary drivers of aging. The thymus shrinks after puberty and is largely non-functional by the 50s, leaving older adults with reduced immune surveillance, impaired clearance of senescent cells, and chronic low-grade inflammation (inflammaging). Thymosin Alpha-1 supplements the signaling function a young thymus performs. In comprehensive longevity protocols, it serves as the "immune layer" — combined with GH peptides, NAD+, and BPC-157 for a multi-system anti-aging approach.`,
    effects: `Effects are subtle and gradual — changes accumulate over 6–12 weeks: getting sick less frequently, faster recovery when ill, reduced chronic fatigue, and greater immune resilience. Patients with chronic infections report improvements in energy and cognitive clarity. Post-COVID patients have found it one of the most consistently promising recovery tools.`,
    protocol: `Standard: 1.6 mg subcutaneous injection 2x/week (e.g., Monday and Thursday). Anti-aging maintenance: 1.6 mg 2x/week for 6–8 weeks, 1–2x per year. Chronic infections: 1.6 mg 2x/week for 6 months minimum. Longevity stack: Thymosin Alpha-1 + NAD+ + CJC-1295/Ipamorelin + BPC-157.`,
    sideEffects: `One of the most favorable safety profiles in peptide medicine. Injection site reactions (mild redness, occasional swelling) are the most common complaint. Extremely well-tolerated across all clinical populations, including cancer patients and immunocompromised individuals.`,
    priceRange: '$179–$399/mo',
    peptideIds: ['thymosin-alpha-1'],
  },
  {
    slug: 'ghk-cu',
    name: 'GHK-Cu',
    subtitle: 'Copper Peptide — Skin, Tissue & Anti-Aging',
    category: 'Anti-Aging & Skin',
    emoji: '✨',
    color: '#D97706',
    bg: '#FFFBEB',
    overview: `GHK-Cu (Glycyl-L-Histidyl-L-Lysine Copper) is the anti-aging peptide that both dermatologists and longevity researchers respect — a rare combination. It's a naturally occurring copper-binding tripeptide your body produces abundantly when young, but levels decline ~60% between ages 20 and 70. Topically, it has one of the most robust evidence bases of any cosmetic ingredient — dozens of studies showing collagen synthesis stimulation, wound healing, and anti-aging effects on skin. Injectable GHK-Cu extends these benefits systemically, remodeling connective tissue and influencing gene expression in ways researchers describe as resetting genes toward a more youthful pattern.`,
    mechanism: `GHK-Cu binds copper ions and delivers them to tissue, activating enzymes involved in collagen and elastin cross-linking. It stimulates fibroblast proliferation and collagen synthesis while regulating matrix metalloproteinases (MMPs) that break down collagen — resulting in more collagen, better-organized collagen, and reduced degradation. It also activates TGF-beta signaling and has been found to influence the expression of over 4,000 human genes, shifting them toward patterns associated with youth, repair, and anti-inflammation.`,
    uses: ['Skin rejuvenation and anti-aging (topical — strongest evidence)', 'Collagen and elastin synthesis', 'Wound healing and scar reduction', 'Hair follicle stimulation', 'Connective tissue repair', 'Injectable systemic anti-aging remodeling'],
    longevity: `GHK-Cu may influence aging at the epigenetic level — the level of gene expression itself. Blood levels at 60 are roughly one-third of levels at 20. Research by Loren Pickart documented that GHK-Cu influences over 4,000 human genes (~31% of the genome), shifting them toward patterns of youth, repair, and anti-inflammation. Genes associated with tumor progression and cellular aging are downregulated; genes for antioxidant defense and repair are upregulated. In longevity protocols it serves as the "tissue and skin layer" — combined with Thymosin Alpha-1, NAD+, and GH peptides for a multi-system approach.`,
    effects: `Topically: consistent improvements in skin texture, firmness, and wrinkle depth within 4–8 weeks. Hair: variable but frequently positive in early-stage thinning. Injectable: improved connective tissue tone, better overall skin quality, and reduced inflammatory markers over 8–12 week courses. Combining topical and injectable GHK-Cu provides the most comprehensive results.`,
    protocol: `Topical (no prescription): apply GHK-Cu serum 1–2x daily to face, neck, and hands. Look for 1–4% concentration. Injectable (prescription required): 1–2 mg subcutaneous 2–3x/week for 8–12 weeks on, 4–6 weeks off. Longevity stack: GHK-Cu injectable + CJC-1295/Ipamorelin + NAD+ + Thymosin Alpha-1.`,
    sideEffects: `Topical: among the safest skincare ingredients known with decades of consumer use. Injectable: standard injection site reactions (mild redness, swelling). Blue-green discoloration reported in older literature is associated with concentrations far above therapeutic doses and is not seen at standard dosing.`,
    priceRange: '$79–$199/mo',
    peptideIds: ['ghk-cu'],
  },slug: 'semaglutide',
    name: 'Semaglutide',
    subtitle: 'GLP-1 Receptor Agonist',
    category: 'Weight Loss',
    emoji: '🏃',
    color: '#0EA5E9',
    bg: '#F0F9FF',
    overview: `Semaglutide is a GLP-1 (glucagon-like peptide-1) receptor agonist originally developed for type 2 diabetes management and now widely prescribed for chronic weight management. It is the active compound in brand-name medications Ozempic, Wegovy, and Rybelsus.`,
    mechanism: `Semaglutide mimics the natural GLP-1 hormone released after meals, stimulating insulin secretion, suppressing glucagon, slowing gastric emptying, and signaling fullness to the brain. These combined effects dramatically reduce caloric intake and regulate blood sugar, producing significant and sustained weight loss.`,
    uses: ['Weight loss & obesity management', 'Type 2 diabetes management', 'Appetite suppression', 'Blood sugar regulation', 'Cardiovascular risk reduction', 'Metabolic syndrome treatment'],
    effects: 'Clinical trials show average weight loss of 15–17% of body weight over 68 weeks. Compounded semaglutide through telehealth providers offers significant cost savings vs brand-name versions. Most users experience noticeable appetite suppression within the first 1–2 weeks.',
    priceRange: '$99–$299/mo',
    peptideIds: ['semaglutide'],
  },
]

// ─────────────────────────────────────────────
// 30 TELEHEALTH PROVIDERS (real companies)
// ─────────────────────────────────────────────
export const providers = [
  {
    id: 'marek-health', slug: 'marek-health', name: 'Marek Health', logo: 'MH',
    rating: 4.9, reviewCount: 1240, featured: true, verified: true, badge: 'Best Overall',
    location: 'Ships nationwide', priceFrom: 149, priceTo: 499,
    website: 'marekhealth.com',
    peptides: ['Sermorelin', 'CJC-1295', 'Ipamorelin', 'BPC-157', 'TB-500', 'PT-141', 'NAD+'],
    highlight: 'Comprehensive lab testing + licensed physician review. Considered the gold standard for online hormone and peptide optimization.',
    pros: ['In-depth lab panels included', 'Licensed physician oversight', 'Transparent pharmacy sourcing', 'Large online community'],
    cons: ['Higher price point', 'Requires bloodwork before starting'],
    discount: 'Free consultation', color: '#1D4ED8',
  },
  {
    id: 'defy-medical', slug: 'defy-medical', name: 'Defy Medical', logo: 'DM',
    rating: 4.8, reviewCount: 980, featured: true, verified: true, badge: 'Best for TRT + Peptides',
    location: 'Ships to 48 states', priceFrom: 175, priceTo: 599,
    website: 'defymedical.com',
    peptides: ['Sermorelin', 'Ipamorelin', 'CJC-1295', 'BPC-157', 'TB-500', 'PT-141', 'Semaglutide'],
    highlight: 'One of the most established telehealth clinics specializing in hormones and peptides with 10+ years of operation.',
    pros: ['Board-certified physicians', 'Extensive peptide protocols', 'TRT + peptide stacks', 'Strong patient community'],
    cons: ['Higher cost', 'Appointment wait times'],
    discount: '$50 OFF first protocol', color: '#059669',
  },
  {
    id: 'evolve-telemed', slug: 'evolve-telemed', name: 'Evolve Telemed', logo: 'ET',
    rating: 4.8, reviewCount: 654, featured: true, verified: true, badge: 'Best Value',
    location: 'Ships to 50 states', priceFrom: 99, priceTo: 349,
    website: 'evolvetelemed.com',
    peptides: ['BPC-157', 'Sermorelin', 'Ipamorelin', 'CJC-1295', 'NAD+', 'Semaglutide'],
    highlight: 'Competitive pricing with licensed providers and fast turnaround. Excellent for first-time peptide patients.',
    pros: ['Affordable entry pricing', 'Same-day consultations available', 'Quick prescription processing'],
    cons: ['Fewer advanced peptides', 'Limited stacking protocols'],
    discount: '20% OFF first order', color: '#7C3AED',
  },
  {
    id: 'peptide-vitality', slug: 'peptide-vitality', name: 'Peptide Vitality', logo: 'PV',
    rating: 4.7, reviewCount: 432, featured: false, verified: true, badge: 'Best for Recovery',
    location: 'Ships to 46 states', priceFrom: 119, priceTo: 379,
    website: 'peptidevitality.com',
    peptides: ['BPC-157', 'TB-500', 'Ipamorelin', 'CJC-1295', 'GHK-Cu'],
    highlight: 'Recovery-focused protocols designed by sports medicine physicians. Preferred by athletes and active adults.',
    pros: ['Sports medicine expertise', 'BPC-157 + TB-500 stacks', 'Athlete-focused dosing', 'Injury-specific protocols'],
    cons: ['Limited weight loss options', 'Fewer metabolic peptides'],
    discount: 'Free performance assessment', color: '#DC2626',
  },
  {
    id: 'heally', slug: 'heally', name: 'Heally', logo: 'HE',
    rating: 4.7, reviewCount: 1876, featured: false, verified: true, badge: 'Most Accessible',
    location: 'Ships to 50 states', priceFrom: 89, priceTo: 299,
    website: 'getheally.com',
    peptides: ['Sermorelin', 'BPC-157', 'Ipamorelin', 'PT-141', 'NAD+', 'Semaglutide', 'TB-500'],
    highlight: 'Large telehealth platform with competitive pricing and broad peptide access. Easiest onboarding process reviewed.',
    pros: ['Lowest consultation fees', 'Wide peptide menu', 'Fast same-day approvals', 'User-friendly app'],
    cons: ['Less personalized protocols', 'Standardized dosing only'],
    discount: '$25 OFF first consultation', color: '#10B981',
  },
  {
    id: 'biorestoration', slug: 'biorestoration', name: 'BioRestoration', logo: 'BR',
    rating: 4.7, reviewCount: 328, featured: false, verified: true, badge: 'Best Longevity Focus',
    location: 'Ships to 45 states', priceFrom: 189, priceTo: 599,
    website: 'biorestoration.com',
    peptides: ['Epitalon', 'NAD+', 'Sermorelin', 'CJC-1295', 'Ipamorelin', 'Thymosin Alpha-1'],
    highlight: 'Specializes in advanced longevity and anti-aging protocols including Epitalon and Thymosin Alpha-1.',
    pros: ['Rare peptides available', 'Longevity specialists', 'In-depth consultations', 'Anti-aging focus'],
    cons: ['Premium pricing', 'Complex onboarding'],
    discount: 'Free longevity consultation', color: '#0F172A',
  },
  {
    id: 'joy-md', slug: 'joy-md', name: 'Joy MD', logo: 'JM',
    rating: 4.6, reviewCount: 543, featured: false, verified: true, badge: 'Best for Women',
    location: 'Ships to 47 states', priceFrom: 129, priceTo: 449,
    website: 'joymd.co',
    peptides: ['Semaglutide', 'PT-141', 'BPC-157', 'Sermorelin', 'NAD+', 'Ipamorelin'],
    highlight: "Women's health-focused telehealth with dedicated female providers and protocols tailored to women's physiology.",
    pros: ["Women's health specialty", 'Female providers available', 'HSDD treatment', 'Weight loss + hormones'],
    cons: ['Limited sports medicine peptides', 'Higher price for specialty protocols'],
    discount: '15% OFF with code WINNER15', color: '#EC4899',
  },
  {
    id: 'regenx-health', slug: 'regenx-health', name: 'RegenX Health', logo: 'RX',
    rating: 4.6, reviewCount: 287, featured: false, verified: true, badge: 'Best NAD+ Provider',
    location: 'Ships to 44 states', priceFrom: 199, priceTo: 599,
    website: 'regenxhealth.com',
    peptides: ['NAD+', 'Sermorelin', 'CJC-1295', 'Ipamorelin', 'BPC-157', 'MOTS-c'],
    highlight: 'Leading specialist in NAD+ therapy and mitochondrial optimization. Also offers a full range of hormone peptides.',
    pros: ['NAD+ specialists', 'IV and injectable NAD+', 'Mitochondrial protocols', 'Cognitive enhancement focus'],
    cons: ['Premium pricing for NAD+', 'Requires extensive intake forms'],
    discount: 'Free NAD+ consultation', color: '#F59E0B',
  },
  {
    id: 'ways2well', slug: 'ways2well', name: 'Ways2Well', logo: 'W2',
    rating: 4.6, reviewCount: 412, featured: false, verified: true, badge: 'Best Functional Medicine',
    location: 'Ships to 48 states', priceFrom: 159, priceTo: 499,
    website: 'ways2well.com',
    peptides: ['BPC-157', 'Sermorelin', 'Ipamorelin', 'CJC-1295', 'NAD+', 'Semaglutide', 'PT-141'],
    highlight: 'Functional medicine approach with comprehensive biomarker testing and personalized peptide protocols.',
    pros: ['Functional medicine focus', 'Comprehensive lab work', 'Personalized dosing', 'Ongoing monitoring'],
    cons: ['Higher upfront lab cost', 'Longer onboarding'],
    discount: '$75 OFF first lab panel', color: '#0891B2',
  },
  {
    id: 'transformyou', slug: 'transformyou', name: 'TransformYou', logo: 'TY',
    rating: 4.6, reviewCount: 376, featured: false, verified: true, badge: 'Best in Arizona',
    location: 'AZ + Telehealth (38 states)', priceFrom: 139, priceTo: 449,
    website: 'transformyou.com',
    peptides: ['BPC-157', 'Sermorelin', 'CJC-1295', 'Ipamorelin', 'TB-500', 'AOD-9604', 'MOTS-c'],
    highlight: '15+ years experience in weight loss and peptide therapy. In-office and telehealth options available.',
    pros: ['In-person + telehealth', '15+ years experience', 'AOD-9604 available', 'MOTS-c protocols'],
    cons: ['In-office primarily in AZ', 'Limited coast-to-coast coverage'],
    discount: '10% OFF first protocol', color: '#D97706',
  },
  {
    id: 'numan', slug: 'numan', name: 'Numan', logo: 'NU',
    rating: 4.5, reviewCount: 892, featured: false, verified: true, badge: "Best Men's Health",
    location: 'US + International', priceFrom: 99, priceTo: 349,
    website: 'numan.com',
    peptides: ['Semaglutide', 'PT-141', 'Sermorelin', 'BPC-157', 'CJC-1295'],
    highlight: "Men's health telehealth platform covering peptides, TRT, ED, and metabolic health.",
    pros: ["Men's health specialty", 'ED treatment + peptides', 'Affordable pricing', 'Discrete shipping'],
    cons: ['Men only', 'Limited women\'s peptide protocols'],
    discount: 'Free first consultation', color: '#1E293B',
  },
  {
    id: 'hydramed', slug: 'hydramed', name: 'HydraMed RX', logo: 'HY',
    rating: 4.5, reviewCount: 298, featured: false, verified: true, badge: 'Fast Shipping',
    location: 'Ships to 46 states', priceFrom: 109, priceTo: 399,
    website: 'hydramed.com',
    peptides: ['Semaglutide', 'BPC-157', 'Sermorelin', 'Ipamorelin', 'NAD+', 'TB-500'],
    highlight: 'Quick prescription processing with 2–3 day shipping from licensed compounding pharmacies.',
    pros: ['Fast prescription turnaround', '2–3 day shipping', 'Licensed pharmacy partners', 'Transparent pricing'],
    cons: ['Newer provider (2022)', 'Fewer reviews than top tier'],
    discount: 'Free shipping on first order', color: '#0EA5E9',
  },
  {
    id: 'amazing-meds', slug: 'amazing-meds', name: 'Amazing Meds', logo: 'AM',
    rating: 4.5, reviewCount: 543, featured: false, verified: true, badge: 'Best Hormones + Peptides',
    location: 'Ships to 44 states', priceFrom: 149, priceTo: 499,
    website: 'amazing-meds.com',
    peptides: ['Sermorelin', 'CJC-1295', 'Ipamorelin', 'NAD+', 'Semaglutide', 'BPC-157', 'PT-141'],
    highlight: 'Combines BHRT, hormone optimization, and peptide therapy under one comprehensive platform.',
    pros: ['BHRT + peptide combo', 'Board-certified physicians', 'Comprehensive hormone testing', 'Good patient support'],
    cons: ['Pricing not always transparent upfront', 'Long consultation wait'],
    discount: 'Complimentary hormone consultation', color: '#7C3AED',
  },
  {
    id: 'readyrx', slug: 'readyrx', name: 'ReadyRx', logo: 'RR',
    rating: 4.5, reviewCount: 187, featured: false, verified: true, badge: 'Best for Sermorelin',
    location: 'Ships to 45 states', priceFrom: 129, priceTo: 349,
    website: 'readyrx.com',
    peptides: ['Sermorelin', 'CJC-1295', 'Ipamorelin', 'BPC-157'],
    highlight: 'Sermorelin specialists with injectable and dissolving tablet (ODT) formulation options.',
    pros: ['ODT + injectable options', 'Sermorelin specialists', 'Competitive pricing', 'Clean onboarding'],
    cons: ['Limited peptide variety', 'Newer platform'],
    discount: '$30 OFF first order', color: '#059669',
  },
  {
    id: 'bridgeside-telehealth', slug: 'bridgeside-telehealth', name: 'Bridgeside Telehealth', logo: 'BT',
    rating: 4.5, reviewCount: 214, featured: false, verified: true, badge: 'Comprehensive Menu',
    location: 'Ships to 40 states', priceFrom: 119, priceTo: 449,
    website: 'bridgesidetelehealth.com',
    peptides: ['BPC-157', 'TB-500', 'Sermorelin', 'Ipamorelin', 'PT-141', 'Tesamorelin', 'Selank'],
    highlight: 'One of the broadest peptide menus in telehealth, including rare options like Selank and Tesamorelin.',
    pros: ['Selank & Tesamorelin available', 'Broad peptide selection', 'Licensed providers', 'Personalized protocols'],
    cons: ['Not available in all states', 'Less brand recognition'],
    discount: 'Free first consultation', color: '#0F766E',
  },
  {
    id: 'better-med-spa', slug: 'better-med-spa', name: 'Better Med Spa', logo: 'BM',
    rating: 4.5, reviewCount: 165, featured: false, verified: true, badge: 'Best in Illinois',
    location: 'IL + Telehealth (35 states)', priceFrom: 149, priceTo: 499,
    website: 'bettermedspa.com',
    peptides: ['Sermorelin', 'CJC-1295', 'Ipamorelin', 'Semaglutide', 'BPC-157', 'MOTS-c', 'PT-141'],
    highlight: 'Premium telehealth and in-office care combining GLP-1, hormones, and advanced peptide therapy.',
    pros: ['In-office option in Chicago', 'Comprehensive protocols', 'MOTS-c available', 'TRT + peptide stacks'],
    cons: ['Primarily Midwest focused', 'Premium pricing'],
    discount: '10% OFF first month', color: '#BE185D',
  },
  {
    id: 'relive-health', slug: 'relive-health', name: 'Relive Health', logo: 'RH',
    rating: 4.5, reviewCount: 731, featured: false, verified: true, badge: 'In-Clinic + Telehealth',
    location: '60+ US locations + telehealth', priceFrom: 159, priceTo: 549,
    website: 'relivehealth.com',
    peptides: ['BPC-157', 'Sermorelin', 'CJC-1295', 'Ipamorelin', 'NAD+', 'Semaglutide', 'TB-500'],
    highlight: '60+ clinic locations nationwide with telehealth option. Trusted thousands of patients with in-person accountability.',
    pros: ['60+ physical locations', 'In-person option', 'Medical-grade compounds', 'Strong track record'],
    cons: ['Inconsistent experience by location', 'Pricier than pure telehealth'],
    discount: 'Free location consultation', color: '#0369A1',
  },
  {
    id: 'limitless-life-nootropics', slug: 'limitless-life', name: 'Limitless Life Nootropics', logo: 'LL',
    rating: 4.4, reviewCount: 892, featured: false, verified: true, badge: 'Research Peptides',
    location: 'Online only — research use', priceFrom: 39, priceTo: 199,
    website: 'limitlesslifenootropics.com',
    peptides: ['BPC-157', 'TB-500', 'CJC-1295', 'Ipamorelin', 'PT-141', 'Epithalon', 'GHK-Cu'],
    highlight: 'Research-grade peptides for verified researchers. Note: requires verification — not a clinical provider.',
    pros: ['Low cost research peptides', 'Wide selection', 'Third-party testing', 'Fast shipping'],
    cons: ['Research use only', 'Not a licensed prescriber', 'No medical oversight'],
    discount: '15% OFF with code RESEARCH15', color: '#374151',
  },
  {
    id: 'fountain-life', slug: 'fountain-life', name: 'Fountain Life', logo: 'FL',
    rating: 4.7, reviewCount: 342, featured: false, verified: true, badge: 'Premium Longevity',
    location: 'Select US cities + telehealth', priceFrom: 499, priceTo: 2500,
    website: 'fountainlife.com',
    peptides: ['NAD+', 'Sermorelin', 'CJC-1295', 'Ipamorelin', 'BPC-157', 'Thymosin Alpha-1', 'Epitalon'],
    highlight: 'Ultra-premium longevity medicine with comprehensive diagnostics, full-body scans, and elite peptide protocols.',
    pros: ['Comprehensive diagnostics', 'Elite medical team', 'Full-body health picture', 'Advanced longevity protocols'],
    cons: ['Very high cost', 'Limited locations'],
    discount: 'Complimentary health screening', color: '#0C4A6E',
  },
  {
    id: 'gameday-mens-health', slug: 'gameday-mens-health', name: "Gameday Men's Health", logo: 'GM',
    rating: 4.5, reviewCount: 612, featured: false, verified: true, badge: "Men's Optimization",
    location: '55+ US locations + telehealth', priceFrom: 149, priceTo: 449,
    website: 'gamedaymenshealth.com',
    peptides: ['Sermorelin', 'CJC-1295', 'Ipamorelin', 'BPC-157', 'PT-141', 'Semaglutide'],
    highlight: "Men's optimization clinics specializing in TRT, peptides, and performance. 55+ locations nationwide.",
    pros: ['55+ locations', 'TRT + peptide combos', "Men's health specialists", 'Sports medicine focus'],
    cons: ['Men only', 'Inconsistent pricing by location'],
    discount: 'Free testosterone check', color: '#1E3A5F',
  },
  {
    id: 'biolounge', slug: 'biolounge', name: 'BioLounge', logo: 'BL',
    rating: 4.5, reviewCount: 198, featured: false, verified: true, badge: 'IV + Peptide Therapy',
    location: 'Select US cities + telehealth', priceFrom: 179, priceTo: 699,
    website: 'biolounge.com',
    peptides: ['NAD+', 'Sermorelin', 'BPC-157', 'TB-500', 'Ipamorelin', 'GHK-Cu'],
    highlight: 'Combines IV therapy (NAD+, glutathione, Myers cocktail) with subcutaneous peptide therapy.',
    pros: ['IV + peptide combo', 'NAD+ IV available', 'Holistic protocols', 'Luxury experience'],
    cons: ['Premium pricing', 'In-person IV requires local visit'],
    discount: 'Free wellness consultation', color: '#6D28D9',
  },
  {
    id: 'concierge-md', slug: 'concierge-md', name: 'Concierge MD', logo: 'CM',
    rating: 4.6, reviewCount: 445, featured: false, verified: true, badge: 'In-Home Service',
    location: 'LA + NYC + telehealth', priceFrom: 249, priceTo: 899,
    website: 'conciergemdla.com',
    peptides: ['NAD+', 'BPC-157', 'Sermorelin', 'TB-500', 'Semaglutide', 'Ipamorelin'],
    highlight: 'Concierge medicine with in-home IV and injection services in LA and NYC, plus nationwide telehealth.',
    pros: ['In-home service available', 'Concierge experience', 'IV + injectable peptides', 'Top-tier physicians'],
    cons: ['Very high cost', 'LA/NYC in-home only'],
    discount: 'Free initial telehealth visit', color: '#0F172A',
  },
  {
    id: 'peptide-sciences', slug: 'peptide-sciences', name: 'Peptide Sciences', logo: 'PS',
    rating: 4.4, reviewCount: 1543, featured: false, verified: false, badge: 'Research Grade',
    location: 'Online — research use', priceFrom: 29, priceTo: 149,
    website: 'peptidesciences.com',
    peptides: ['BPC-157', 'TB-500', 'CJC-1295', 'Ipamorelin', 'PT-141', 'Epithalon', 'GHK-Cu', 'Selank'],
    highlight: 'One of the most established research peptide suppliers. Third-party tested. For research use only.',
    pros: ['Lowest prices for research', 'Third-party CoA testing', 'Huge selection', 'Fast shipping'],
    cons: ['Research use only (not clinical)', 'No prescriber on staff'],
    discount: 'Volume discounts available', color: '#334155',
  },
  {
    id: 'vibrant-health-vip', slug: 'vibrant-health-vip', name: 'Vibrant Health VIP', logo: 'VH',
    rating: 4.5, reviewCount: 234, featured: false, verified: true, badge: 'Holistic Approach',
    location: 'Ships to 44 states', priceFrom: 169, priceTo: 549,
    website: 'vibranthealthvip.com',
    peptides: ['Sermorelin', 'NAD+', 'BPC-157', 'Ipamorelin', 'PT-141', 'CJC-1295'],
    highlight: 'Integrates peptide therapy with functional nutrition, lifestyle coaching, and biomarker monitoring.',
    pros: ['Holistic health coaching', 'Nutrition integration', 'Ongoing monitoring', 'Personalized plans'],
    cons: ['More time commitment required', 'Higher touch = higher cost'],
    discount: 'Free wellness assessment', color: '#16A34A',
  },
  {
    id: 'invigor-medical', slug: 'invigor-medical', name: 'Invigor Medical', logo: 'IM',
    rating: 4.4, reviewCount: 687, featured: false, verified: true, badge: 'Budget Friendly',
    location: 'Ships to 46 states', priceFrom: 79, priceTo: 299,
    website: 'invigormedical.com',
    peptides: ['Sermorelin', 'Ipamorelin', 'BPC-157', 'Semaglutide', 'PT-141', 'NAD+'],
    highlight: 'One of the most affordable licensed telehealth peptide providers. Good for budget-conscious patients.',
    pros: ['Very competitive pricing', 'Licensed providers', 'Wide state availability', 'Simple process'],
    cons: ['Less personalized protocols', 'Fewer advanced peptides'],
    discount: '$40 OFF with code PEPTIDE40', color: '#B45309',
  },
  {
    id: 'beyond-wellness', slug: 'beyond-wellness', name: 'Beyond Wellness', logo: 'BW',
    rating: 4.4, reviewCount: 321, featured: false, verified: true, badge: 'Integrative Medicine',
    location: 'TX + Telehealth (42 states)', priceFrom: 149, priceTo: 499,
    website: 'beyondwellnessradio.com',
    peptides: ['BPC-157', 'TB-500', 'Sermorelin', 'NAD+', 'CJC-1295', 'Ipamorelin', 'Thymosin Alpha-1'],
    highlight: 'Integrative functional medicine focused on root cause treatment with peptides as part of a whole-body protocol.',
    pros: ['Root cause approach', 'Functional medicine MD', 'Thymosin Alpha-1 available', 'Autoimmune focus'],
    cons: ['Texas HQ — telehealth expansion ongoing', 'Slower onboarding'],
    discount: 'Free 15-min intro call', color: '#065F46',
  },
  {
    id: 'age-management-medical', slug: 'age-management-medical', name: 'Age Management Medical Group', logo: 'AG',
    rating: 4.6, reviewCount: 412, featured: false, verified: true, badge: 'Anti-Aging Specialists',
    location: 'Multiple US cities + telehealth', priceFrom: 249, priceTo: 799,
    website: 'agemanagementmedical.com',
    peptides: ['Sermorelin', 'CJC-1295', 'Ipamorelin', 'Epitalon', 'NAD+', 'BPC-157', 'Thymosin Alpha-1'],
    highlight: 'Dedicated age management specialists with in-depth diagnostics, comprehensive hormone panels, and advanced longevity peptides.',
    pros: ['Anti-aging specialists', 'Epitalon protocols', 'Comprehensive diagnostics', 'Personalized medicine'],
    cons: ['Premium pricing', 'Requires commitment to full program'],
    discount: 'Complimentary age assessment', color: '#1E1B4B',
  },
  {
    id: 'hormone-zone', slug: 'hormone-zone', name: 'The Hormone Zone', logo: 'HZ',
    rating: 4.5, reviewCount: 529, featured: false, verified: true, badge: 'Hormone + Peptide Expert',
    location: 'AZ + nationwide telehealth', priceFrom: 179, priceTo: 599,
    website: 'hormonezone.com',
    peptides: ['Sermorelin', 'CJC-1295', 'Ipamorelin', 'NAD+', 'BPC-157', 'Semaglutide', 'PT-141'],
    highlight: 'Dr. Donovitz-led practice combining bioidentical hormones with advanced peptide therapy.',
    pros: ['Physician-led', 'Bioidentical + peptide combo', 'Strong reputation', 'Patient community'],
    cons: ['AZ in-person only', 'Premium consultation fees'],
    discount: 'Free hormone evaluation', color: '#831843',
  },
  {
    id: 'the-trt-doctor', slug: 'the-trt-doctor', name: 'The TRT Doctor', logo: 'TD',
    rating: 4.5, reviewCount: 384, featured: false, verified: true, badge: 'TRT + Peptide Stack',
    location: 'Ships to 45 states', priceFrom: 149, priceTo: 499,
    website: 'thetrtdoctor.com',
    peptides: ['Sermorelin', 'CJC-1295', 'Ipamorelin', 'BPC-157', 'PT-141', 'TB-500'],
    highlight: 'Specializes in combining testosterone replacement therapy with complementary peptide protocols.',
    pros: ['TRT + peptide stacks', 'Experienced physicians', 'Comprehensive labs', 'Men\'s optimization focus'],
    cons: ['Male-focused', 'TRT required for some protocols'],
    discount: 'Free testosterone consultation', color: '#1C3A5E',
  },
  {
    id: 'peptide-therapy-network', slug: 'peptide-therapy-network', name: 'Peptide Therapy Network', logo: 'PT',
    rating: 4.3, reviewCount: 167, featured: false, verified: true, badge: 'Provider Directory',
    location: 'Nationwide directory', priceFrom: 99, priceTo: 399,
    website: 'peptidetherapynetwork.com',
    peptides: ['BPC-157', 'Sermorelin', 'Ipamorelin', 'CJC-1295', 'TB-500', 'NAD+'],
    highlight: 'Matches patients with local and telehealth peptide providers based on goals and location.',
    pros: ['Provider matching service', 'Good for finding local options', 'Educational resources', 'Free matching'],
    cons: ['Quality varies by matched provider', 'Not a direct provider'],
    discount: 'Free provider matching', color: '#64748B',
  },
]

// ─────────────────────────────────────────────
// COMPOUNDING PHARMACIES
// ─────────────────────────────────────────────
export const pharmacies = [
  {
    slug: 'empower-pharmacy',
    name: 'Empower Pharmacy',
    logo: 'EP',
    rating: 4.8,
    reviewCount: 1240,
    location: 'Houston, TX',
    states: 50,
    accreditation: ['PCAB', 'USP 797/800'],
    peptides: ['Sermorelin', 'CJC-1295', 'Ipamorelin', 'BPC-157', 'Semaglutide', 'NAD+', 'PT-141'],
    highlight: 'One of the largest 503A compounding pharmacies in the US. PCAB accredited with state-of-the-art clean rooms.',
    pros: ['PCAB accredited', 'Serves all 50 states', 'In-house testing', 'Largest compounding infrastructure'],
    color: '#1D4ED8',
    website: 'empowerpharmacy.com',
  },
  {
    slug: 'pavilion-compounding',
    name: 'Pavilion Compounding Pharmacy',
    logo: 'PC',
    rating: 4.7,
    reviewCount: 412,
    location: 'Atlanta, GA',
    states: 48,
    accreditation: ['PCAB', 'USP 797'],
    peptides: ['BPC-157', 'TB-500', 'Sermorelin', 'Ipamorelin', 'CJC-1295', 'PT-141'],
    highlight: 'Specializes in sterile compounding with rigorous quality control. Preferred pharmacy for several major telehealth platforms.',
    pros: ['Sterile compounding specialists', 'Rigorous QC', 'Telehealth partner preferred', 'CoA with every order'],
    color: '#059669',
    website: 'pavilionpharmacy.com',
  },
  {
    slug: 'pc-rx-compounding',
    name: 'PC Rx Compounding',
    logo: 'PR',
    rating: 4.7,
    reviewCount: 287,
    location: 'Las Vegas, NV',
    states: 45,
    accreditation: ['PCAB', 'USP 797/800'],
    peptides: ['Sermorelin', 'CJC-1295', 'Ipamorelin', 'BPC-157', 'NAD+', 'Semaglutide'],
    highlight: 'PCAB-accredited peptide specialists with fast 2–3 business day shipping to most states.',
    pros: ['Fast shipping', 'PCAB accredited', 'Competitive pricing', 'Good patient portal'],
    color: '#7C3AED',
    website: 'pcrxcompounding.com',
  },
  {
    slug: 'south-florida-compounding',
    name: 'South Florida Compounding',
    logo: 'SF',
    rating: 4.6,
    reviewCount: 198,
    location: 'Fort Lauderdale, FL',
    states: 42,
    accreditation: ['USP 797', 'FL Licensed'],
    peptides: ['BPC-157', 'TB-500', 'Sermorelin', 'Ipamorelin', 'PT-141', 'NAD+'],
    highlight: 'Florida-based sterile compounding pharmacy specializing in peptide formulations with overnight shipping available.',
    pros: ['Overnight shipping available', 'FL-based (Fort Lauderdale)', 'Peptide specialists', 'Good pricing'],
    color: '#0EA5E9',
    website: 'sfcompounding.com',
  },
  {
    slug: 'olympia-pharmacy',
    name: 'Olympia Pharmacy',
    logo: 'OP',
    rating: 4.7,
    reviewCount: 876,
    location: 'Orlando, FL',
    states: 48,
    accreditation: ['PCAB', 'USP 797/800'],
    peptides: ['Sermorelin', 'CJC-1295', 'Ipamorelin', 'BPC-157', 'Semaglutide', 'Tirzepatide', 'NAD+'],
    highlight: 'Major 503A/503B compounder serving thousands of patients and dozens of telehealth platforms. Excellent GLP-1 and peptide pricing.',
    pros: ['503A + 503B capabilities', 'Competitive pricing', 'GLP-1 specialists', 'Broad peptide menu'],
    color: '#B45309',
    website: 'olympiapharmacy.com',
  },
  {
    slug: 'innovagen-pharmacy',
    name: 'Innovagen Pharmacy',
    logo: 'IN',
    rating: 4.6,
    reviewCount: 143,
    location: 'Scottsdale, AZ',
    states: 40,
    accreditation: ['USP 797', 'AZ Licensed'],
    peptides: ['BPC-157', 'TB-500', 'CJC-1295', 'Ipamorelin', 'NAD+', 'Epitalon', 'GHK-Cu'],
    highlight: 'Arizona-based specialty compounder with rare peptides including Epitalon and GHK-Cu. Partner pharmacy for multiple longevity clinics.',
    pros: ['Rare peptides available', 'Longevity focus', 'AZ longevity clinic partner', 'Quality packaging'],
    color: '#D97706',
    website: 'innovagenpharmacy.com',
  },
  {
    slug: 'wellness-pharmacy',
    name: 'The Wellness Pharmacy',
    logo: 'WP',
    rating: 4.5,
    reviewCount: 234,
    location: 'Austin, TX',
    states: 44,
    accreditation: ['PCAB', 'USP 797'],
    peptides: ['Sermorelin', 'Ipamorelin', 'BPC-157', 'Semaglutide', 'PT-141', 'NAD+'],
    highlight: 'Austin-based PCAB pharmacy focused on clean, minimally-formulated peptide preparations.',
    pros: ['Minimalist formulations', 'Clean ingredients', 'Good pricing', 'TX / regional specialization'],
    color: '#16A34A',
    website: 'thewellnesspharmacy.com',
  },
  {
    slug: 'hallandale-pharmacy',
    name: 'Hallandale Pharmacy',
    logo: 'HP',
    rating: 4.6,
    reviewCount: 567,
    location: 'Hallandale Beach, FL',
    states: 46,
    accreditation: ['PCAB', 'USP 797/800'],
    peptides: ['Sermorelin', 'CJC-1295', 'Ipamorelin', 'BPC-157', 'Semaglutide', 'NAD+', 'TB-500', 'PT-141'],
    highlight: 'One of the most established peptide compounders in the Southeast. Serves major national telehealth platforms.',
    pros: ['Well established', 'Full peptide menu', 'National telehealth partner', 'Good track record'],
    color: '#0F766E',
    website: 'hallandalepharmacy.com',
  },
]

// ─────────────────────────────────────────────
// ARTICLES (with unique body content per article)
// ─────────────────────────────────────────────
export const articles = [
  {
    slug: 'what-is-bpc-157',
    title: 'What is BPC-157? Complete Guide for Beginners',
    excerpt: 'BPC-157 is one of the most studied peptides for injury recovery and gut health. Here is everything you need to know before starting.',
    category: 'PEPTIDE SCIENCE',
    readTime: '8 min read',
    date: 'Mar 4, 2026',
    author: 'Dr. James Chen',
    authorTitle: 'Sports Medicine Physician',
    image: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=600&q=80',
    peptideTags: ['BPC-157'],
    body: `BPC-157 stands for Body Protection Compound-157, a synthetic peptide consisting of 15 amino acids. It was first isolated from human gastric juice and has been the subject of extensive preclinical research for its remarkable healing properties.\n\nIn animal models, BPC-157 has demonstrated the ability to accelerate healing of tendons, ligaments, muscles, and the gastrointestinal tract. Researchers believe it works through several mechanisms, including the upregulation of growth hormone receptors, stimulation of angiogenesis (new blood vessel formation), and modulation of nitric oxide production.\n\nFor athletes and active individuals, BPC-157 has become one of the most sought-after peptides for accelerating recovery from sports injuries. Common applications include tendon and ligament repair, muscle healing, and post-surgical recovery. Users typically report noticeable improvements in pain levels and mobility within 2–4 weeks of starting a protocol.\n\nBeyond musculoskeletal healing, BPC-157 has shown significant promise for gastrointestinal health. Its origin in gastric juice suggests an innate role in gut protection and repair, and many users report significant improvements in conditions like leaky gut, IBS, and GERD.\n\nImportantly, BPC-157 requires a prescription from a licensed physician when used in human protocols in the United States. Any provider offering it without a proper medical consultation should be avoided. All providers listed on PeptideWinner require a full online consultation before dispensing BPC-157.`,
  },
  {
    slug: 'sermorelin-vs-ipamorelin',
    title: 'Sermorelin vs Ipamorelin: Which Growth Hormone Peptide Is Right for You?',
    excerpt: 'Both stimulate growth hormone release, but they work differently. We break down the evidence on efficacy, cost, and who each is best for.',
    category: 'COMPARISONS',
    readTime: '11 min read',
    date: 'Feb 28, 2026',
    author: 'Dr. Sarah Mills',
    authorTitle: 'Endocrinologist',
    image: 'https://images.unsplash.com/photo-1559757175-5700dde675bc?w=600&q=80',
    peptideTags: ['Sermorelin', 'Ipamorelin'],
    body: `Both sermorelin and ipamorelin are growth hormone secretagogues — compounds that stimulate the pituitary gland to produce and release growth hormone. But they work through different mechanisms, have different dosing schedules, and are suited to different patient profiles.\n\nSermorelin is a GHRH analog, meaning it mimics the natural growth hormone-releasing hormone produced by your hypothalamus. It directly stimulates the pituitary gland's GHRH receptors. Because it works through the same pathway as natural GHRH, sermorelin maintains the body's natural feedback loops, making it a very physiologically appropriate option for GH optimization.\n\nIpamorelin is a GHRP (growth hormone releasing peptide) and ghrelin receptor agonist. It works through a different pathway — the ghrelin receptor system — to stimulate GH release. What distinguishes ipamorelin from older GHRPs is its high selectivity: it stimulates GH release without significantly affecting cortisol, prolactin, or other hormones, making it one of the cleanest GH-releasing peptides available.\n\nIn practice, these two peptides are frequently combined. The CJC-1295/Ipamorelin stack (CJC-1295 is a long-acting GHRH analog similar to sermorelin) has become one of the most popular peptide protocols in telehealth. The combination works synergistically to produce amplified GH pulses by stimulating both the GHRH and ghrelin pathways simultaneously.\n\nFor cost-conscious patients starting out, sermorelin is typically less expensive and represents an excellent entry point into GH optimization. For those seeking a more comprehensive protocol or who have used sermorelin before, the ipamorelin stack is often the natural next step.`,
  },
  {
    slug: 'nad-plus-benefits',
    title: 'NAD+ Therapy: The Science Behind the Anti-Aging Molecule',
    excerpt: 'NAD+ levels decline with age. Here is what the research actually says about peptide-adjacent NAD+ therapies.',
    category: 'LONGEVITY',
    readTime: '9 min read',
    date: 'Feb 20, 2026',
    author: 'Dr. Michael Torres',
    authorTitle: 'Longevity Medicine Specialist',
    image: 'https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=600&q=80',
    peptideTags: ['NAD+'],
    body: `NAD+ (Nicotinamide Adenine Dinucleotide) is a coenzyme found in every living cell, essential for over 500 enzymatic reactions including those that produce cellular energy (ATP) and repair DNA. It plays a central role in processes linked to aging, and its decline with age has become one of the most researched targets in longevity medicine.\n\nResearch from the labs of David Sinclair at Harvard and Johan Auwerx at EPFL has helped establish that NAD+ levels decline by approximately 50% between ages 20 and 50, and that restoring NAD+ levels in animal models can reverse multiple hallmarks of aging including mitochondrial dysfunction, DNA damage accumulation, and cellular senescence.\n\nNAD+ works as a cofactor for sirtuins — a family of proteins often called "longevity genes" — and PARPs, which are critical DNA repair enzymes. When NAD+ levels are adequate, sirtuins and PARPs function optimally, helping maintain genomic stability, regulate metabolism, and support cellular stress responses.\n\nIn clinical practice, NAD+ is delivered via IV infusion or subcutaneous injection. IV NAD+ produces more immediate effects — patients often report a rapid boost in energy, mental clarity, and even mood — but subcutaneous administration offers more sustainable, gradual improvements in cellular energy and cognitive function.\n\nFor telehealth patients, subcutaneous NAD+ or oral NAD+ precursors (like NMN and NR) offer the most accessible starting points. Providers like RegenX Health and Concierge MD specialize in NAD+ optimization and can guide patients through the most appropriate delivery method based on their goals and budget.`,
  },
  {
    slug: 'bpc-157-tb500-stack',
    title: 'The BPC-157 + TB-500 Stack: Why Athletes Call It the "Wolverine Protocol"',
    excerpt: 'Combining BPC-157 and TB-500 has become the go-to recovery stack for serious athletes. Here\'s the science behind why they work so well together.',
    category: 'STACKING PROTOCOLS',
    readTime: '10 min read',
    date: 'Mar 1, 2026',
    author: 'Dr. Alex Rodriguez',
    authorTitle: 'Sports Medicine & Regenerative Medicine',
    image: 'https://images.unsplash.com/photo-1538805060514-97d9cc17730c?w=600&q=80',
    peptideTags: ['BPC-157', 'TB-500'],
    body: `The combination of BPC-157 and TB-500 has earned the nickname "Wolverine Protocol" among biohackers and athletes — a reference to the Marvel character's near-instantaneous healing ability. While the nickname is hyperbolic, the research supporting this combination is genuinely impressive.\n\nBPC-157 and TB-500 work through complementary and synergistic mechanisms. BPC-157 primarily acts locally — it is most effective when administered close to an injury site and excels at repairing tendons, ligaments, and the gastrointestinal tract. TB-500, by contrast, is systemic — it distributes throughout the body via the bloodstream and is particularly effective for widespread inflammation and cardiac tissue.\n\nTB-500 (a synthetic analog of Thymosin Beta-4) works by upregulating actin, promoting cell migration to injury sites, stimulating angiogenesis, and reducing chronic inflammation. When combined with BPC-157's local tissue repair effects, the two peptides address injury recovery from both a systemic and localized perspective simultaneously.\n\nPractitioners who prescribe this combination report that patients with complex musculoskeletal injuries — rotator cuff tears, partial ACL tears, chronic tendinopathies — often experience dramatically accelerated recovery timelines compared to standard-of-care approaches alone. The protocol is typically run for 4–6 weeks, often alongside physical therapy.\n\nFor athletes considering this stack, Peptide Vitality and Evolve Telemed are among the providers that specialize in recovery-focused stacking protocols and can help design a BPC-157/TB-500 program appropriate to your specific injury and goals.`,
  },
  {
    slug: 'semaglutide-compounded-vs-brand',
    title: 'Compounded Semaglutide vs. Ozempic/Wegovy: What\'s the Real Difference?',
    excerpt: 'Compounded semaglutide can cost 80% less than brand-name Ozempic. But is it as safe and effective? We break down the facts.',
    category: 'WEIGHT LOSS',
    readTime: '12 min read',
    date: 'Feb 25, 2026',
    author: 'Dr. Rachel Kim',
    authorTitle: 'Metabolic Medicine Specialist',
    image: 'https://images.unsplash.com/photo-1550831107-1553da8c8464?w=600&q=80',
    peptideTags: ['Semaglutide'],
    body: `The active pharmaceutical ingredient in Ozempic and Wegovy — semaglutide — can now be obtained through licensed compounding pharmacies at a fraction of the brand-name cost. A monthly supply of Wegovy at retail can exceed $1,000, while compounded semaglutide through telehealth providers typically runs $99–$299/month. The question patients rightly ask is: what's the actual difference?\n\nChemically, compounded semaglutide contains the same active ingredient (semaglutide) as Ozempic and Wegovy, prepared by licensed 503A compounding pharmacies from pharmaceutical-grade raw materials. The key difference is that compounded medications are not FDA-approved finished products — they are patient-specific preparations made by pharmacies operating under a different regulatory framework than mass-manufactured drugs.\n\nThis distinction matters in practice. High-quality compounding pharmacies — PCAB accredited, using USP 797/800 clean rooms, performing in-house quality testing — produce compounded semaglutide that is chemically identical to the brand name product in terms of active ingredient. Lower-quality operations may cut corners on sterility, purity testing, or ingredient sourcing.\n\nThe FDA has taken action against pharmacies producing adulterated or mislabeled compounded semaglutide, which underscores the importance of choosing providers who use only accredited pharmacies. On PeptideWinner, all listed providers are verified to use PCAB-accredited or equivalent licensed compounders.\n\nFor most patients who cannot afford or access Ozempic/Wegovy, compounded semaglutide from a reputable telehealth provider represents a legitimate and significantly more affordable pathway to the same active treatment. Providers like Heally, Evolve Telemed, and Vitality Clinic Online are among those with strong compounded semaglutide programs.`,
  },
  {
    slug: 'pt-141-guide',
    title: 'PT-141 Complete Guide: The Peptide for Sexual Health',
    excerpt: 'PT-141 is the only FDA-approved peptide that works through the central nervous system to enhance sexual desire. Here\'s everything you need to know.',
    category: 'SEXUAL HEALTH',
    readTime: '7 min read',
    date: 'Feb 15, 2026',
    author: 'Dr. Jessica Park',
    authorTitle: 'Sexual Medicine Specialist',
    image: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=600&q=80',
    peptideTags: ['PT-141'],
    body: `PT-141 (Bremelanotide) is unique among prescription peptides because it is the only compound that treats sexual dysfunction through the central nervous system rather than the vascular system. While drugs like Viagra and Cialis improve blood flow to sexual organs, PT-141 works directly on the brain pathways responsible for sexual desire and arousal.\n\nPT-141 is an agonist of melanocortin receptors (MC3R and MC4R) in the hypothalamus. These receptors are part of the neural circuits governing sexual motivation, and activating them produces a direct enhancement of libido and arousal in both men and women. The FDA-approved version (Vyleesi) is licensed for premenopausal women with Hypoactive Sexual Desire Disorder (HSDD).\n\nFor men, PT-141 is used off-label for erectile dysfunction, particularly in cases where psychological factors or low libido are contributing to the dysfunction — areas where PDE5 inhibitors are less effective. Many men report that PT-141 produces not just physical response but also enhanced desire, which they describe as qualitatively different from the effects of Viagra or Cialis.\n\nFor women, PT-141 addresses one of the most common forms of sexual dysfunction — lack of desire — which PDE5 inhibitors do not treat. Clinical studies showed significant improvements in sexual desire and distress scores in women with HSDD.\n\nPT-141 is typically administered as a subcutaneous injection 45–90 minutes before sexual activity, with effects lasting 6–12 hours. Side effects are generally mild, with temporary facial flushing and nausea being the most commonly reported. Joy MD and Heally are among the top-rated providers for PT-141 prescriptions.`,
  },
]

// ─────────────────────────────────────────────
// REVIEWS
// ─────────────────────────────────────────────
export const reviews = [
  { name: 'Marcus T.', location: 'Austin, TX', provider: 'Marek Health', rating: 5, text: 'BPC-157 completely transformed my knee recovery after surgery. 3 months to full strength vs the 9 months my surgeon predicted.', peptide: 'BPC-157', avatar: 'MT' },
  { name: 'Sarah K.', location: 'Denver, CO', provider: 'Defy Medical', rating: 5, text: 'Sermorelin protocol for 4 months. My sleep quality went from a 4/10 to a consistent 8/10. Energy levels are back to where they were in my 20s.', peptide: 'Sermorelin', avatar: 'SK' },
  { name: 'James R.', location: 'Miami, FL', provider: 'Heally', rating: 5, text: 'Lost 34 lbs in 5 months on their semaglutide protocol. The support team was incredible — text them anytime.', peptide: 'Semaglutide', avatar: 'JR' },
  { name: 'Emily C.', location: 'Seattle, WA', provider: 'BioRestoration', rating: 4, text: 'Very professional experience from consultation to delivery. Thymosin Alpha-1 has helped my autoimmune symptoms considerably.', peptide: 'NAD+', avatar: 'EC' },
  { name: 'David M.', location: 'Chicago, IL', provider: 'Peptide Vitality', rating: 5, text: 'As a competitive cyclist, the TB-500 + BPC-157 stack cut my recovery time between hard training blocks by at least 40%.', peptide: 'TB-500', avatar: 'DM' },
  { name: 'Lisa P.', location: 'Phoenix, AZ', provider: 'TransformYou', rating: 5, text: 'Finally a telehealth service that actually tells you which pharmacy compounds your peptides. Huge trust factor.', peptide: 'CJC-1295', avatar: 'LP' },
  { name: 'Ryan B.', location: 'Nashville, TN', provider: 'Ways2Well', rating: 5, text: 'Comprehensive lab panel before starting, then a truly personalized protocol. This is how it should be done.', peptide: 'Ipamorelin', avatar: 'RB' },
  { name: 'Amanda W.', location: 'Boston, MA', provider: 'Joy MD', rating: 5, text: 'PT-141 is genuinely life-changing. Joy MD made the consultation completely comfortable and non-judgmental.', peptide: 'PT-141', avatar: 'AW' },
  { name: 'Chris L.', location: 'San Diego, CA', provider: 'Evolve Telemed', rating: 4, text: 'The 24/7 support chat is not just a bot — actual nurses answer within minutes. Worth every penny for the peace of mind.', peptide: 'BPC-157', avatar: 'CL' },
  { name: 'Jennifer H.', location: 'Atlanta, GA', provider: 'Marek Health', rating: 5, text: 'I have tried 3 different peptide providers over 2 years. Marek Health has the most comprehensive protocols and the best monitoring.', peptide: 'NAD+', avatar: 'JH' },
  { name: 'Kevin S.', location: 'Portland, OR', provider: 'Defy Medical', rating: 5, text: 'CJC-1295/Ipamorelin stack. Lean muscle gains over 12 weeks that I had not seen in years of training.', peptide: 'Ipamorelin', avatar: 'KS' },
  { name: 'Nicole A.', location: 'Dallas, TX', provider: 'RegenX Health', rating: 5, text: 'NAD+ IV plus subcutaneous — the clarity I felt after the first IV session was unlike anything I had experienced. PeptideWinner helped me find a legitimate provider.', peptide: 'NAD+', avatar: 'NA' },
]

// ─────────────────────────────────────────────
// FAQS
// ─────────────────────────────────────────────
export const faqs = [
  { question: 'Are peptide therapies legal in the United States?', answer: 'Yes, most peptide therapies are legal in the US when prescribed by a licensed physician and compounded by an FDA-registered pharmacy. PeptideWinner only lists providers who operate within current regulations.' },
  { question: 'How does PeptideWinner make money?', answer: 'PeptideWinner earns a referral commission from providers when you use our links to sign up. This never affects our rankings — providers are ranked based on verified patient reviews, pricing transparency, and pharmacy sourcing quality. We always disclose our affiliate relationships.' },
  { question: 'How do you verify the providers listed on PeptideWinner?', answer: 'We verify each provider\'s medical licensing, pharmacy partnerships, pricing transparency, and responsiveness to patient complaints. Providers must submit documentation before listing and are reviewed quarterly.' },
  { question: 'How much does peptide therapy typically cost?', answer: 'Entry-level protocols typically run $89–$299/month. Advanced stacking protocols can reach $400–$600/month. Our filter tools let you sort by budget.' },
  { question: 'Do I need a prescription for peptide therapy?', answer: 'Yes. All compounded peptides require a valid prescription from a licensed physician. Any provider offering peptides without a consultation is operating outside the law. All providers on PeptideWinner require an online consultation before dispensing.' },
  { question: 'What is the best peptide for weight loss?', answer: 'Semaglutide and Tirzepatide are currently the most evidence-backed peptides for weight loss. Use our quiz to get matched to the right provider for your weight loss goals.' },
  { question: 'What is the best peptide for injury recovery?', answer: 'BPC-157 is the most studied peptide for injury recovery, particularly for tendons, ligaments, and gut healing. TB-500 is often stacked with BPC-157 for enhanced systemic recovery.' },
  { question: 'Can I trust online peptide reviews?', answer: 'Reviews on PeptideWinner are submitted directly by patients and are moderated for authenticity. We never allow providers to pay for positive reviews.' },
]
