export const providers = [
  {
    id: 'alpha-longevity', slug: 'alpha-longevity', name: 'Alpha Longevity Health', logo: 'AL',
    rating: 4.9, reviewCount: 312, featured: true, verified: true, badge: 'Best Overall',
    location: 'Ships to 48 states', priceFrom: 149, priceTo: 399,
    peptides: ['BPC-157', 'TB-500', 'Sermorelin', 'CJC-1295'],
    highlight: 'Transparent pricing, licensed pharmacy sourcing, dedicated health coaches.',
    pros: ['FDA-registered pharmacy', 'No hidden fees', 'Free shipping over $200'],
    cons: ['Requires lab work for some peptides'],
    discount: '20% OFF first order', color: '#0EA5E9',
  },
  {
    id: 'peptide-md', slug: 'peptide-md', name: 'PeptideMD', logo: 'PM',
    rating: 4.8, reviewCount: 198, featured: true, verified: true, badge: 'Best Value',
    location: 'Ships to 45 states', priceFrom: 99, priceTo: 299,
    peptides: ['Ipamorelin', 'BPC-157', 'PT-141', 'NAD+'],
    highlight: 'Physician-supervised protocols at the best prices in the industry.',
    pros: ['Lowest prices verified', 'Same-day consultations', 'HSA/FSA accepted'],
    cons: ['Limited to select peptides', 'No auto-ship program'],
    discount: '$50 OFF first protocol', color: '#059669',
  },
  {
    id: 'renew-life', slug: 'renew-life', name: 'RenewLife Telehealth', logo: 'RL',
    rating: 4.7, reviewCount: 445, featured: false, verified: true, badge: 'Most Reviews',
    location: 'Ships to 50 states', priceFrom: 179, priceTo: 449,
    peptides: ['Sermorelin', 'CJC-1295/Ipamorelin', 'Thymosin Alpha-1', 'MOTS-c'],
    highlight: 'Largest selection of anti-aging peptide protocols with ongoing medical oversight.',
    pros: ['Widest peptide selection', 'Anti-aging specialists', 'Quarterly check-ins included'],
    cons: ['Higher price point', 'Longer onboarding process'],
    discount: 'Free consultation', color: '#7C3AED',
  },
  {
    id: 'apex-health', slug: 'apex-health', name: 'Apex Performance Health', logo: 'AP',
    rating: 4.7, reviewCount: 156, featured: false, verified: true, badge: 'Best for Athletes',
    location: 'Ships to 42 states', priceFrom: 199, priceTo: 599,
    peptides: ['TB-500', 'BPC-157', 'IGF-1 LR3', 'GHK-Cu'],
    highlight: 'Performance-focused protocols designed by sports medicine physicians.',
    pros: ['Sports medicine focus', 'Recovery optimization', 'Stacking protocols available'],
    cons: ['Premium pricing', 'Not ideal for weight loss goals'],
    discount: 'Free performance assessment', color: '#DC2626',
  },
  {
    id: 'vitality-clinic', slug: 'vitality-clinic', name: 'Vitality Clinic Online', logo: 'VC',
    rating: 4.6, reviewCount: 287, featured: false, verified: true, badge: 'Best Support',
    location: 'Ships to 46 states', priceFrom: 129, priceTo: 349,
    peptides: ['Semaglutide', 'Tirzepatide', 'BPC-157', 'Ipamorelin'],
    highlight: '24/7 patient support team with dedicated nurse practitioners on call.',
    pros: ['24/7 support', 'Weight loss specialty', 'Monthly monitoring included'],
    cons: ['Waitlist during peak periods'],
    discount: '15% OFF with code WINNER15', color: '#D97706',
  },
  {
    id: 'genesis-health', slug: 'genesis-health', name: 'Genesis Health Solutions', logo: 'GH',
    rating: 4.5, reviewCount: 103, featured: false, verified: true, badge: 'New & Rising',
    location: 'Ships to 38 states', priceFrom: 89, priceTo: 279,
    peptides: ['BPC-157', 'Sermorelin', 'CJC-1295', 'Epitalon'],
    highlight: 'New provider with aggressive pricing and cutting-edge longevity protocols.',
    pros: ['Lowest entry price', 'Longevity focus', 'Epitalon available'],
    cons: ['Newer provider (2023)', 'Fewer reviews'],
    discount: '25% OFF launch pricing', color: '#0F3460',
  },
]

export const reviews = [
  { name: 'Marcus T.', location: 'Austin, TX', provider: 'Alpha Longevity', rating: 5, text: 'BPC-157 completely transformed my knee recovery after surgery. 3 months to full strength vs the 9 months my surgeon predicted.', peptide: 'BPC-157', avatar: 'MT' },
  { name: 'Sarah K.', location: 'Denver, CO', provider: 'PeptideMD', rating: 5, text: 'Sermorelin protocol for 4 months. My sleep quality went from a 4/10 to a consistent 8/10. Energy levels are back to where they were in my 20s.', peptide: 'Sermorelin', avatar: 'SK' },
  { name: 'James R.', location: 'Miami, FL', provider: 'Vitality Clinic', rating: 5, text: 'Lost 34 lbs in 5 months on their semaglutide protocol. The support team was incredible — text them anytime.', peptide: 'Semaglutide', avatar: 'JR' },
  { name: 'Emily C.', location: 'Seattle, WA', provider: 'RenewLife', rating: 4, text: 'Very professional experience from consultation to delivery. Thymosin Alpha-1 has helped my autoimmune symptoms considerably.', peptide: 'Thymosin Alpha-1', avatar: 'EC' },
  { name: 'David M.', location: 'Chicago, IL', provider: 'Apex Performance', rating: 5, text: 'As a competitive cyclist, the TB-500 + BPC-157 stack cut my recovery time between hard training blocks by at least 40%.', peptide: 'TB-500', avatar: 'DM' },
  { name: 'Lisa P.', location: 'Phoenix, AZ', provider: 'Alpha Longevity', rating: 5, text: 'Finally a telehealth service that actually tells you which pharmacy compounds your peptides. Huge trust factor.', peptide: 'CJC-1295', avatar: 'LP' },
  { name: 'Ryan B.', location: 'Nashville, TN', provider: 'Genesis Health', rating: 5, text: 'New provider but extremely impressed. Doctor was knowledgeable and the onboarding was smooth.', peptide: 'Ipamorelin', avatar: 'RB' },
  { name: 'Amanda W.', location: 'Boston, MA', provider: 'PeptideMD', rating: 5, text: 'PT-141 is genuinely life-changing. PeptideMD made the consultation completely comfortable and non-judgmental.', peptide: 'PT-141', avatar: 'AW' },
  { name: 'Chris L.', location: 'San Diego, CA', provider: 'Vitality Clinic', rating: 4, text: 'The 24/7 support chat is not just a bot — actual nurses answer within minutes. Worth every penny for the peace of mind.', peptide: 'BPC-157', avatar: 'CL' },
  { name: 'Jennifer H.', location: 'Atlanta, GA', provider: 'RenewLife', rating: 5, text: 'I have tried 3 different peptide providers over 2 years. RenewLife has the most comprehensive protocols and the best monitoring.', peptide: 'MOTS-c', avatar: 'JH' },
  { name: 'Kevin S.', location: 'Portland, OR', provider: 'Apex Performance', rating: 5, text: 'IGF-1 LR3 protocol under their guidance. Lean muscle gains over 12 weeks that I had not seen in years of training.', peptide: 'IGF-1 LR3', avatar: 'KS' },
  { name: 'Nicole A.', location: 'Dallas, TX', provider: 'Alpha Longevity', rating: 5, text: 'GHK-Cu for skin and the results are remarkable. PeptideWinner helped me find a legitimate provider.', peptide: 'GHK-Cu', avatar: 'NA' },
]

export const articles = [
  {
    slug: 'what-is-bpc-157',
    title: 'What is BPC-157? Complete Guide for Beginners',
    excerpt: 'BPC-157 is one of the most studied peptides for injury recovery and gut health. Here is everything you need to know before starting.',
    category: 'PEPTIDE SCIENCE', readTime: '8 min read', date: 'Mar 4, 2026',
    author: 'Dr. James Chen', image: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=600&q=80',
  },
  {
    slug: 'sermorelin-vs-ipamorelin',
    title: 'Sermorelin vs Ipamorelin: Which Growth Hormone Peptide Is Right for You?',
    excerpt: 'Both stimulate growth hormone release, but they work differently. We break down the evidence on efficacy, cost, and who each is best for.',
    category: 'COMPARISONS', readTime: '11 min read', date: 'Feb 28, 2026',
    author: 'Dr. Sarah Mills', image: 'https://images.unsplash.com/photo-1559757175-5700dde675bc?w=600&q=80',
  },
  {
    slug: 'nad-plus-benefits',
    title: 'NAD+ Therapy: The Science Behind the Anti-Aging Molecule',
    excerpt: 'NAD+ levels decline with age. Here is what the research actually says about peptide-adjacent NAD+ therapies.',
    category: 'LONGEVITY', readTime: '9 min read', date: 'Feb 20, 2026',
    author: 'Dr. Michael Torres', image: 'https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=600&q=80',
  },
]

export const faqs = [
  { question: 'Are peptide therapies legal in the United States?', answer: 'Yes, most peptide therapies are legal in the US when prescribed by a licensed physician and compounded by an FDA-registered pharmacy. PeptideWinner only lists providers who operate within current regulations.' },
  { question: 'How does PeptideWinner make money?', answer: 'PeptideWinner earns a referral commission from providers when you use our links to sign up. This never affects our rankings — providers are ranked based on verified patient reviews, pricing transparency, and pharmacy sourcing quality. We always disclose our affiliate relationships.' },
  { question: 'How do you verify the providers listed on PeptideWinner?', answer: 'We verify each provider\'s medical licensing, pharmacy partnerships, pricing transparency, and responsiveness to patient complaints. Providers must submit documentation before listing and are reviewed quarterly.' },
  { question: 'How much does peptide therapy typically cost?', answer: 'Entry-level protocols typically run $89–$299/month. Advanced stacking protocols can reach $400–$600/month. Our filter tools let you sort by budget.' },
  { question: 'Do I need a prescription for peptide therapy?', answer: 'Yes. All compounded peptides require a valid prescription from a licensed physician. Any provider offering peptides without a consultation is operating outside the law. All providers on PeptideWinner require an online consultation before dispensing.' },
  { question: 'What is the best peptide for weight loss?', answer: 'Semaglutide and Tirzepatide are currently the most evidence-backed peptides for weight loss. Use our quiz to get matched to the right provider for your weight loss goals.' },
  { question: 'What is the best peptide for injury recovery?', answer: 'BPC-157 is the most studied peptide for injury recovery, particularly for tendons, ligaments, and gut healing. TB-500 is often stacked with BPC-157 for enhanced systemic recovery.' },
  { question: 'Can I trust online peptide reviews?', answer: 'Reviews on PeptideWinner are submitted directly by patients and are moderated for authenticity. We never allow providers to pay for positive reviews.' },
]
